import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import { useEffect, useState } from 'react'
import { json } from 'stream/consumers'
import Typewriter from 'typewriter-effect';
import { Modal } from 'antd'
import Link from 'next/link'


const inter = Inter({ subsets: ['latin'] })

export default function Home() {
    const [image, setImage] = useState("https://mdbootstrap.com/img/new/standard/nature/182.jpg");
    const [title, setTitle] = useState("Lorem ipsum");
    const [story, setStory] = useState("Lorem ipsum Lorem ipsum Lorem ipsum dolor Lorem ipsum Lorem ipsum Lorem ipsum dolor ipsum dolor ipsum dolor Lorem ipsum Lorem ipsum Lorem ipsum dolor ipsum dolor ipsum dolor Lorem ipsum Lorem ipsum Lorem ipsum dolor ipsum dolor ipsum dolor ipsum dolor ipsum dolor ipsum dolor ipsum ipsum dolor dolor");
    const [fullCard, setFullCard] = useState([])
    /*{ image: image, title: title, stroy: story }*/
    const [inputs, setInputs] = useState({});
    const [alertSuccesShowHide, setAlertSuccesShowHide] = useState(false)
    const [iconInfoShowHide, setIconInfoShowHide] = useState(false)
    const [imageInfoShowHide, setImageInfoShowHide] = useState(false)
    const handleChange = (event) => {
        const name = event.target.name;
        const value = event.target.value;
        setInputs(values => ({ ...values, [name]: value }))
        setAlertSuccesShowHide(false)
    }

    const handleSubmit = (event) => {
        event.preventDefault();
        setFullCard(current => [...current, inputs]);
        setAlertSuccesShowHide(true)
        localStorage.setItem("myObject", JSON.stringify(fullCard))
    }
    useEffect(() => {
        localStorage.setItem("myObject", JSON.stringify(fullCard))
        // Perform localStorage action
        let newObject = window.localStorage.getItem("myObject");
        console.log(JSON.parse(newObject));

    })
    console.log(fullCard)
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
                <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.0/css/all.min.css" integrity="sha512-xh6O/CkQoPOWDdYTDqeRdPCVd1SpvCA9XXcUnZS2FmJNp1coAFzvtCN9BmamE+4aHK8yyUHUSCcJHgXloTyT2A==" crossorigin="anonymous" referrerpolicy="no-referrer" />
                <link href="https://fonts.googleapis.com/css?family=Waiting+for+the+Sunrise" rel="stylesheet" type="text/css" />
                <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css" integrity="sha512-9usAa10IRO0HhonpyAIVpjrylPvoDwiPUiKdWk5t3PyolY1cOd4DSE0Ga+ri4AuTroPR5aQvXU9xC6qOPnzFeg==" crossorigin="anonymous" referrerpolicy="no-referrer" />
            </Head>
            <main className={styles.main}>
                <div className="flex justify-center createCardCss">
                    <div className="rounded-lg shadow-lg bg-white max-w-sm">
                        <form onSubmit={handleSubmit}>
                            <h2 class="mb-4 text-3xl font-extrabold leading-none tracking-tight text-gray-900 md:text-4xl dark:text-white text-center"><button onClick={() => setImageInfoShowHide(!imageInfoShowHide)} type="button">IMAGE<i class="fa-solid fa-question"></i></button></h2>
                            {imageInfoShowHide ?
                                <div>
                                    <div class="grid grid-rows-1 grid-flow-col gap-4 pl-3">
                                        <div>
                                            <h6 class="text-lg font-bold dark:text-white">Koyacak arkaplaniniz yok ise default image: </h6>
                                            https://pusat.edu.np/wp-content/uploads/2022/09/default-image.jpg
                                        </div>
                                    </div>
                                </div> :
                                null
                            }
                            <textarea
                                className="w-full"
                                type="text"
                                name="image"
                                onChange={handleChange}
                            />
                            <hr></hr>
                            <div className="p-6">
                                <h2 class="mb-4 text-3xl font-extrabold leading-none tracking-tight text-gray-900 md:text-4xl dark:text-white text-center">TITLE</h2>
                                <textarea
                                    className="w-full"
                                    type="text"
                                    name="title"
                                    onChange={handleChange}
                                />
                                <h2 class="mb-4 text-3xl font-extrabold leading-none tracking-tight text-gray-900 md:text-4xl dark:text-white text-center">STORY</h2>
                                <textarea
                                    className="w-full"
                                    type="text"
                                    name="story"
                                    onChange={handleChange}
                                />
                            </div>
                            <hr></hr>
                            <div className="container  py-8">
                                <div className="grid grid-cols-3 gap-4">
                                    <div>
                                        <h2 class="mb-4 text-3xl font-extrabold leading-none tracking-tight text-gray-900 md:text-xl dark:text-white text-center"><button onClick={() => setIconInfoShowHide(!iconInfoShowHide)} type="button">BUTTON 1<i class="fa-solid fa-question"></i></button></h2>
                                        {iconInfoShowHide ?
                                            <div>
                                                <div class="grid grid-rows-6 grid-flow-col gap-4 pl-3">
                                                    <div>
                                                        <h6 class="text-lg font-bold dark:text-white">fa-solid fa-shield-halved fa-3x</h6>
                                                        <i class="fa-solid fa-shield-halved"></i>
                                                    </div>
                                                    <div>
                                                        <h6 class="text-lg font-bold dark:text-white">fa-solid fa-biohazard fa-3x</h6>
                                                        <i class="fa-solid fa-biohazard"></i>
                                                    </div>
                                                    <div>
                                                        <h6 class="text-lg font-bold dark:text-white">fa-solid fa-burger fa-3x</h6>
                                                        <i class="fa-solid fa-burger"></i>
                                                    </div>
                                                    <div>
                                                        <h6 class="text-lg font-bold dark:text-white">fa-solid fa-droplet fa-3x</h6>
                                                        <i class="fa-solid fa-droplet"></i>
                                                    </div>
                                                    <div>
                                                        <h6 class="text-lg font-bold dark:text-white">fa-solid fa-eye-slash fa-3x</h6>
                                                        <i class="fa-solid fa-eye-slash"></i>
                                                    </div>
                                                    <div>
                                                        <h6 class="text-lg font-bold dark:text-white">fa-regular fa-moon fa-3x</h6>
                                                        <i class="fa-regular fa-moon"></i>
                                                    </div>
                                                </div>
                                            </div> :
                                            null
                                        }
                                        <input
                                            className="w-full"
                                            type="text"
                                            name="button1"
                                            onChange={handleChange}
                                        />
                                        <textarea
                                            className="w-full"
                                            type="text"
                                            name="btn1mean"
                                            onChange={handleChange}
                                        />
                                    </div>
                                    <div>
                                        <h2 class="mb-4 text-3xl font-extrabold leading-none tracking-tight text-gray-900 md:text-xl dark:text-white text-center">BUTTON 2</h2>
                                        <input
                                            className="w-full"
                                            type="text"
                                            name="button2"
                                            onChange={handleChange}
                                        />
                                        <textarea
                                            className="w-full"
                                            type="text"
                                            name="btn2mean"
                                            onChange={handleChange}
                                        />
                                    </div>
                                    <div>
                                        <h2 class="mb-4 text-3xl font-extrabold leading-none tracking-tight text-gray-900 md:text-xl dark:text-white text-center">BUTTON 3</h2>
                                        <input
                                            className="w-full"
                                            type="text"
                                            name="button3"
                                            onChange={handleChange}
                                        />
                                        <textarea
                                            className="w-full"
                                            type="text"
                                            name="btn3mean"
                                            onChange={handleChange}
                                        />
                                    </div>
                                </div>
                                <div className="grid grid-cols-3 gap-4 py-14">
                                    <div></div>
                                    <div className="text-center">
                                        <button className="bg-white hover:bg-gray-100 text-gray-800 font-semibold py-2 px-4 border border-gray-400 rounded shadow">
                                            <input type="submit" />
                                        </button>
                                    </div>
                                    <div></div>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
                {alertSuccesShowHide ? <div className="mt-5 flex p-4 mb-4 text-sm text-green-800 border border-green-300 rounded-lg bg-green-50 dark:bg-gray-800 dark:text-green-400 dark:border-green-800" role="alert">
                    <svg aria-hidden="true" className="flex-shrink-0 inline w-5 h-5 mr-3" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M18 10a8 8 0 11-16 0 8 8 0 0116 0zm-7-4a1 1 0 11-2 0 1 1 0 012 0zM9 9a1 1 0 000 2v3a1 1 0 001 1h1a1 1 0 100-2v-3a1 1 0 00-1-1H9z" clip-rule="evenodd"></path></svg>
                    <span className="sr-only">Info</span>
                    <div>
                        <span className="font-medium">Success alert!</span> Hikaye kartinizi basarili bir sekilde olusturdunuz.
                    </div>
                </div> : null}
                <h1>
                    {fullCard.length}: kart olusturdunuz
                </h1>
                <button class="bg-red-500 hover:bg-blue-400 text-white font-bold py-2 px-4 border-b-4 border-red-800 hover:border-blue-500 rounded">
                    <a href="/story/firstStory">Hikayeyi Baslat</a>
                </button>
            </main>
        </>
    )
}
