import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "@/styles/Home.module.css";
import Typewriter from "typewriter-effect";
import { useRouter } from "next/router";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
    const router = useRouter()
    return (
        <>
            <Head>
                <title>Matrix Text</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
                <link
                    href="https://fonts.googleapis.com/css?family=Waiting+for+the+Sunrise"
                    rel="stylesheet"
                    type="text/css"
                />
            </Head>
            <main className="h-full">
                <style global jsx>{`
                  html,
                  body,
                  body > div:first-child,
                  div#__next,
                  div#__next > div {
                    height: 100%;
                  }
                `}</style>
                <div className="bg-gradient-to-t from-black to-red-700 text-2xl h-full font-extrabold shadow-xl shadow-red-700">
                    <div className="bg-gray-900 shadow-2xl shadow-black text-2xl text-center py-6">
                        <p className="text-white font-serif font-extrabold">Last Day On Earth</p>
                    </div>
                    <Typewriter
                        onInit={(typewriter) => {
                            typewriter
                                .typeString(
                                    "<h1 style='color: white; margin:30px; font-family:Waiting for the Sunrise, cursive; '>'Yil 2024. Insanlik korona virusunu atlattigin icin sevinclidir.Her sey normale donmustur.Fakat bu sevinc cok uzun surmemistir.Yeni bir vaka patlak verir fakat bu oncekinden farklidir.Yakalanan kisilerde fiziksel ve ruhsal degisimler gorulmustur.Vakaya yakalanmis kisiler adeta zombilesmis gibi hareket ediyorlardir.Virus eskisindende hizli tum dunyaya yayilmaya baslamistir. [Virus isirilma ve kan yolu ile bulasicidir][Virus adi Papatya Yusufi]Her ne kadar onune gecilmeye calisilsada maalesef basarisiz olunmustur.Insanlarin ya cogusu virus tarafidan ele gecirilmis ya da hayatta kalmak icin mucadele etmektedir.Hayatta kalanlar icinde sartlar eskisi gibi degildir.Erzaklar azalmis, elektrikler kesilmis, sular kirlenmis, insanlar hayatta kalmak icin vahsilesmis, dunya adeta 'yasan bir olu olmustur.' Yusufi de hayatta kalmaya calisanlardan biridir.Peki yusufi gercekten hayatta kalmayi basarabilicek mi ??? </h1>"
                                )
                                .callFunction(() => {
                                    console.log("String typed out!");
                                })
                                .pauseFor(500)
                                // .deleteAll()
                                .callFunction(() => {
                                    console.log("All strings were deleted");
                                })
                                .start();
                        }}
                        options={{
                            autoStart: true,
                            loop: false,
                            delay: 5,
                        }}
                    />
                    <footer>
                        <button
                            onClick={() => router.push("/story/0")}
                            type="button"
                            className="absolute bottom-0 right-0 h-14 w-12 text-red-700 border border-red-700 hover:bg-red-700 hover:text-white focus:ring-4 focus:outline-none focus:ring-red-700 font-large rounded-lg text-large p-2.5 text-center inline-flex items-center mr-2 dark:border-red-700 dark:text-red-700 dark:hover:text-white dark:focus:ring-red-800"
                        >
                            <svg
                                aria-hidden="true"
                                className="w-5 h-5"
                                fill="currentColor"
                                viewBox="0 0 20 20"
                                xmlns="http://www.w3.org/2000/svg"
                            >
                                <path
                                    fill-rule="evenodd"
                                    d="M10.293 3.293a1 1 0 011.414 0l6 6a1 1 0 010 1.414l-6 6a1 1 0 01-1.414-1.414L14.586 11H3a1 1 0 110-2h11.586l-4.293-4.293a1 1 0 010-1.414z"
                                    clip-rule="evenodd"
                                >
                                </path>
                            </svg>
                            <span className="sr-only">Icon description</span>
                        </button>
                    </footer>
                </div>
            </main>
        </>
    );
}
